/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Chips: typeof import('primevue/chips')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    HeroSection: typeof import('./src/components/home/isNotAuth/heroSection.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    IsAuthHome: typeof import('./src/components/home/isAuth/isAuthHome.vue')['default']
    IsNotAut: typeof import('./src/components/home/isNotAuth/isNotAut.vue')['default']
    IsNotAuth: typeof import('./src/components/home/isNotAuth/index.vue')['default']
    IsNotAutHome: typeof import('./src/components/home/isNotAuth/isNotAutHome.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NewlyPublishedAdvertisementsSection: typeof import('./src/components/home/isNotAuth/newlyPublishedAdvertisementsSection.vue')['default']
    OurBusinessAreasSection: typeof import('./src/components/home/isNotAuth/ourBusinessAreasSection.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    UsInFiguresSection: typeof import('./src/components/home/isNotAuth/usInFiguresSection.vue')['default']
  }
}
